qa_python_sprint
vishenkailya/qa_sprint_2 pull request #3
Opened 2023-06-21 11:09 UTC by vishenkailya

Реализовал 14 тестов

2023-06-21 20:52 UTC, kadirovgm requested changes

2023-06-21 20:52 UTC, kadirovgm commented on .gitignore
> +
Можно лучше: в файле гитигнора лучше оставлять только те локальные файлы, что не должны быть запушены в общий репозиторий, в твоем случае ты использовала общий шаблон, это не совсем верно, мы должны избегать использования ненужного кода в проекте.

2023-06-21 20:52 UTC, kadirovgm commented on README.md
> +test_add_new_book_add_two_books: Добавляем 2 книги
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('rating', [11, 15, 100])
можно лучше: молодец, что пользуешься параметризацией! кажется 11, 15 и 100 это эквивалентные значения класса, и немножко лишнее их все проверять

намного логичнее было бы написать тест с параметризированными данными граничных значений:
-1, 0, 1, 10, 11 например

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating('1984') == rating
в целом все всерно! молодец

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('rating', [11, 15, 100])
нужно исправить: мне кажется эта проверка лишняя, его можно оставить как негативный кейс, но параметризация явно лишняя, мы должны стараться писать максимально мало итераций проверок, которые охватывают наиболее полные проверки

здесь проверки одного значений из данного класса эквивалентности вполне достаточно

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_books_with_specific_rating(10)) == 2
можно лучше: в юнит тестах и в целом в тест-кейсах нужно стараться избегать повторения части проверок из одного тест-кейса в другом, здесь этот тест явно дополнение второго, то есть лучше оставить одно из двух, вполне достаточно теста выше

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +    def test_get_books_rating_2_books(self):
нужно исправить: такой тест уже есть в 7-ой строке: `test_add_new_book_add_two_books`

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +        collector.set_book_rating('Rage', 6)
нужно исправить: лишние строки с set_book_rating, так как тест проверяет добавелние книги в словарь, а не указание книгам рейтинга

2023-06-21 20:52 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 1
можно лучше: здесь корректнее не просто проверить, что в список favorites добавилась одна книга, а добавилась именна нужная нам книга: например, можно с помощью конструкции `in/not in`

2023-06-22 10:15 UTC, vishenkailya commented on tests.py
> +    @pytest.mark.parametrize('rating', [11, 15, 100])
Так 1 и 10 входят в заданный диапазон значений, тогда нужно условие, чтобы их проверить, а в теории говорилось, что лучше так не делать

2023-06-23 19:25 UTC, kadirovgm approved these changes

2023-06-23 19:25 UTC, kadirovgm commented on tests.py
> +#Не увидел, что после каждого замечания надо делать коммит, поэтому случайно закоммитил все изменения сразу
это не обязательно требование, но лучше делать так :)

2023-06-23 19:25 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('rating', [11, 15, 100])
да, я тут просто пример привел, в нашем случае лучше проверять в двух тестах: граничные значения, которые в результате дают 1(-беск;0,11,беск+), и заданный диапазон (1<10)

2023-06-23 19:25 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('rating', [11, -1, 0])
отлично! да, именно это я и имел ввиду, чтобы невалидные значения проверять в одном тесте с параметризацией

2023-06-23 19:25 UTC, kadirovgm commented on tests.py
> +    def test_get_book_with_specific_rating_above_range_empty_massive(self):
отлично! вот этого достаточно

2023-06-23 19:25 UTC, kadirovgm commented on tests.py
> +        assert 'Бойцовский клуб' in collector.get_list_of_favorites_books()
супер!

2023-06-23 19:25 UTC, kadirovgm commented on README.md
> +test.py Тестирует класс BooksCollector
можно лучше: в дальнейшем для описания readme советую пользоваться markdown

2023-06-25 19:20 UTC, merged